### PR TITLE
fix(active-index): resets index if activeIndex doesn't exist

### LINKED ISSUE #3: Reset active gallery item if activeIndex is undefined
Galleries may have a different number of items based on the width of the viewport. In these instances, it's possible for the gallery to attempt to navigate to an undefined index when crossing one of these breakpoint thresholds.

### PR DESCRIPTION
**Pull request by NicholasLancey**
## Description

We discovered an edge case where the `activeIndex` did **not** exist. This often happens if the amount of `GalleryItems` changes based on the viewport width.

## Solution

Adds a check to see if the activeIndex exists, if it doesn't run the `goToIndex()` function and default to 0.

## Note

Fixes #3

### CODE REVIEW

File: src/lib/components/gallery-main.jsx [hunk 1]
```diff
@@ -18,8 +18,13 @@ export const GalleryMain = ({ renderGalleryItem, className, ...props }) => {
     touchState,
     setTouchState,
     swipeThreshold,
+    goToIndex,
   } = useGallery()
 
+  useEffect(() => {
+    if (!galleryItems[activeIndex]) goToIndex(0)
```
Comment (andrewrubin) [inline src/lib/components/gallery-main.jsx:25]: I think we can lose the `useEffect`, and integrate this logic into the actual `goToIndex` function. That thing should be updated to be a bit more defensive anyway. Inside that function, maybe instead of just accepting that `index` is defined, let's first check that it's valid, and if not, set to zero.

I think with this useEffect solution, we'll still briefly get a warning, since side-effects run _after_ the render phase.

Comment (marlonmarcello) [reply src/lib/components/gallery-main.jsx:25]: Agree with this one, otherwise we'll always have to resort to this `useEffect` trick.

**Comment by NicholasLancey** [comment]
A bit of back and fourth with @andrewrubin on this one.

1. I've added a check to validate the index passed through to the `goToIndex` function. That's unrelated to the issue addressed in this PR.
2. I've moved the useEffect to the context. Unfortunately I can't think of another way for this to work - as the function needs to run every time `items` changes.

**Comment by andrewrubin** [comment]
Agreed, thanks for entertaining the idea though. Tested on my end and working. Here's a screencap where `items` changes at 768:


https://github.com/wethegit/react-gallery/assets/30575213/03914509-dd93-4c26-a75c-7f27c8630ba3

**Review by andrewrubin — APPROVED** [review]

**Comment by andrewrubin** [comment]
Merging this one

**Review by andrewrubin — APPROVED** [review]
